(function(){
'use strict';
if(document.getElementById('cslFeedbackButton'))return;
var KEY='csl_feedback_drafts_v1';
function q(s){return document.querySelector(s)}
function currentSentence(){var el=q('#zh')||q('.zh');return el?el.textContent.trim():''}
function pageContext(){return{page:location.pathname.split('/').pop()||'index.html',title:document.title,sentence:currentSentence(),url:location.href,at:new Date().toISOString()}}
function saveDraft(data){var a=[];try{a=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){}a.push(data);localStorage.setItem(KEY,JSON.stringify(a.slice(-100)))}
var st=document.createElement('style');st.textContent='#cslFeedbackButton{position:fixed;right:14px;bottom:84px;z-index:9998;border:0;border-radius:999px;background:#171717;color:#fff;padding:10px 13px;font:700 12px -apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 6px 20px #0002}#cslFeedbackPanel{display:none;position:fixed;inset:0;z-index:9999;background:#0005;padding:18px;align-items:flex-end;justify-content:center}#cslFeedbackPanel.on{display:flex}.cslfb{width:min(620px,100%);background:#f7f5ef;border-radius:26px;padding:18px;max-height:82vh;overflow:auto;font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#171717}.cslfb h3{margin:2px 0 4px;font-size:22px}.cslfb p{font-size:12px;color:#777;line-height:1.55}.cslfb .types{display:flex;gap:7px;flex-wrap:wrap;margin:14px 0}.cslfb .type{border:0;border-radius:999px;padding:10px 12px;background:#ece9e1;font-weight:700}.cslfb .type.on{background:#171717;color:#fff}.cslfb textarea{width:100%;min-height:100px;border:1px solid #ddd7ca;border-radius:16px;padding:12px;font:inherit;background:#fff}.cslfb .row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.cslfb .btn{border:0;border-radius:16px;padding:13px;font-weight:750}.cslfb .send{background:#171717;color:#fff}.cslfb .cancel{background:#e9e6de}.cslfb .status{font-size:12px;color:#596354;margin-top:9px;display:none}';document.head.appendChild(st);
var b=document.createElement('button');b.id='cslFeedbackButton';b.textContent='Feedback';document.body.appendChild(b);
var p=document.createElement('div');p.id='cslFeedbackPanel';p.innerHTML='<div class="cslfb"><h3>気づいたことを教えてください</h3><p>学習履歴は送信しません。現在のページ名と、表示中の中国語があればそれだけを添えます。</p><div class="types"><button class="type" data-v="迷った">迷った</button><button class="type" data-v="分かりにくい">分かりにくい</button><button class="type" data-v="中国語が変かも">中国語が変かも</button><button class="type" data-v="こうしてほしい">こうしてほしい</button><button class="type" data-v="良かった">良かった</button></div><textarea id="cslfbNote" placeholder="短くても大丈夫です"></textarea><div class="row"><button class="btn cancel" id="cslfbCancel">閉じる</button><button class="btn send" id="cslfbSend">共有する</button></div><div class="status" id="cslfbStatus"></div></div>';document.body.appendChild(p);
var type='';p.querySelectorAll('.type').forEach(function(x){x.onclick=function(){p.querySelectorAll('.type').forEach(function(y){y.classList.remove('on')});x.classList.add('on');type=x.dataset.v}});
b.onclick=function(){p.classList.add('on');type='';q('#cslfbNote').value='';p.querySelectorAll('.type').forEach(function(y){y.classList.remove('on')})};q('#cslfbCancel').onclick=function(){p.classList.remove('on')};
q('#cslfbSend').onclick=async function(){var c=pageContext(),note=q('#cslfbNote').value.trim(),data={kind:type||'自由記述',note:note,context:c};saveDraft(data);var text=['Chinese Structure Lab Feedback','種類: '+data.kind,'ページ: '+c.page,(c.sentence?'表示中: '+c.sentence:''),'コメント: '+(note||'なし')].filter(Boolean).join('\n');try{if(navigator.share){await navigator.share({title:'Chinese Structure Lab Feedback',text:text});q('#cslfbStatus').textContent='共有しました。ありがとうございます。';q('#cslfbStatus').style.display='block'}else{await navigator.clipboard.writeText(text);q('#cslfbStatus').textContent='コピーしました。メッセージ等に貼り付けて送れます。';q('#cslfbStatus').style.display='block'}}catch(e){if(e&&e.name==='AbortError')return;try{await navigator.clipboard.writeText(text);q('#cslfbStatus').textContent='コピーしました。';q('#cslfbStatus').style.display='block'}catch(_){window.prompt('この内容をコピーしてください',text)}}};
})();